name: CD-Liara
on:
  push:
    branches:
      - deploy-liara
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '20'
      - name: update-liara
        env:
          LIARA_TOKEN: ${{ secrets.LIARA_API_TOKEN }}
        run: |
          npm i -g @liara/cli@6
          liara deploy --app="work-time-app" --api-token="$LIARA_TOKEN" --no-app-logs --port=9000
